name: Artifact_test
on: push

jobs:
  JOB1:
    name: Artifact creation
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v5.1.0
        
      - name: Current location testing
        run: |
          pwd
          ls -al
          whoami
          hostname
      
      - name: adding files to the system
        run: |
          mkdir artifact
          echo "This is my first task" > b1.txt
          echo "this is what the artifact will be used to create" > artifact/b2.txt
      - name: checking files
        run: |
          pwd
          ls -la
      
      - name: check now 
        run: |
         ls -al
         pwd

      - name: upload
        uses: actions/upload-artifact@v7
        with:
         name: multiple_path 
         path:
           ./b1.txt
           ./artifact/

      - name: Download a Build Artifact 
        uses: actions/download-artifact@v7.0.0 #git market place 
        with: 
          name: multiple_path 
      - name: checking current directory post download 
        run: | 
          pwd 
          ls -al 
           

          
