name: First_workflow 
# this is the workflo name
on: 
  push:

jobs:
  job1:
    name: Check_Basic
    runs-on: ubuntu-latest
    steps:
      - name: Check the current directory and the files in it
        run: |
          pwd
          ls -al
          hostname
      
      - name: Create a folder and file 
        run: |
          mkdir Data
          echo "This is my task to be done on prod" >> ./Data/pic.txt
          cat ./Data/pic.txt
