name: First_workflow 
# this is the workflo name
on: 
# workflow dispatch works for manual trigger the workflow and the schedule worksto run the flow every 5 min
  workflow_dispatch:
  
jobs:
  job1:
    name: Check_Basic
    runs-on: ubuntu-latest
    steps:
      - name: Check the current directory and the files in it
        run: |
          pwd
          ls -al
          hostname
      
      - name: Create a folder and file 
        run: |
          mkdir Data
          echo "This is my task to be done on prod" >> ./Data/pic.txt
          cat ./Data/pic.txt
  job2:
    needs: [job1]
    name: CHCEK THE LIST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0

      - name: testing the data
        run: ls -al
      
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
    # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: '3.11'     

  job3:
    needs: [job1,job2]
    name: Check the python is installed 
    runs-on: ubuntu-latest
    steps:
       - name: Check python
         run: python3 -c 'print("This is the task")'

       - name:
         run: python3 -c 'print("THis is the task to be completed ")
      


  
